name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  ci:
    name: Continuous Integration
    uses: bigbang1112/workflows/.github/workflows/ci.yml@main
    with:
      dotnet-version: 10.x.x
      workloads: wasm-tools