name: Deploy to Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Pages
    uses: bigbang1112/workflows/.github/workflows/deploy-pages.yml@main
    with:
      dotnet-version: 10.x.x
      workloads: wasm-tools
      project: TmScores.Showcase
